version: '3.5'
services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./forum:/var/www/html
    depends_on:
      - web
  web:
    build: .
    volumes:
      - ./forum:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: beehiveforum
      MYSQL_USER: beehiveforum
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password