version: '3.5'
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./forum:/var/www/html
    depends_on:
      - web
  web:
    build: .
    volumes:
      - ./docker/overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./forum:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: beehiveforum
      MYSQL_USER: beehiveforum
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
volumes:
  mysql: