# Main user table
CREATE TABLE USER (
UID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
LOGON CHAR(32),
NICKNAME CHAR(32),
EMAIL VARCHAR(80),
STATUS TINYINT         # 0 = User, 1 = Admin1, 2 = Admin2 etc
);

#Sig held in separate table to keep BLOB value isolated
CREATE TABLE USER_SIG (
UID MEDIUMINT UNSIGNED REFERENCES user,
CONTENT TEXT,
HTML CHAR(1)
);

#Folder lookup
CREATE TABLE FOLDER (
FID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(32)
);

#Thread table
CREATE TABLE THREAD (
TID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
FID MEDIUMINT UNSIGNED REFERENCES folder,
TITLE VARCHAR(64),
POLL_FLAG CHAR(1),
CLOSED DATETIME
);

#Poll table, 1-1 with thread where POLL_FLAG = Y
CREATE TABLE POLL (
TID MEDIUMINT UNSIGNED,
O1 VARCHAR(255),
O1_VOTES MEDIUMINT UNSIGNED,
O2 VARCHAR(255),
O2_VOTES MEDIUMINT UNSIGNED,
O3 VARCHAR(255),
O3_VOTES MEDIUMINT UNSIGNED,
O4 VARCHAR(255),
O4_VOTES MEDIUMINT UNSIGNED,
O5 VARCHAR(255),
O6_VOTES MEDIUMINT UNSIGNED,
CLOSES DATETIME
);

#Post table
CREATE TABLE POST (
PID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,  #Unique within table
TID MEDIUMINT UNSIGNED REFERENCES thread,
POST_NUM MEDIUMINT UNSIGNED,     # Different from PID, only unique within TID (thread id)
REPLY_TO_PID MEDIUMINT UNSIGNED,
FROM_UID MEDIUMINT UNSIGNED REFERENCES user,
TO_UID MEDIUMINT UNSIGNED REFERENCES user,
CREATED TIMESTAMP,
CONTENT TEXT
);

#Attachments detail table
CREATE TABLE POST_ATTACHMENT (
PID MEDIUMINT UNSIGNED REFERENCES post,
FILE VARCHAR(255)
);

#User thread management, holds most recently read post and level of interest
CREATE TABLE USER_THREAD (
UID MEDIUMINT UNSIGNED REFERENCES user,
TID MEDIUMINT UNSIGNED REFERENCES thread,
LAST_READ MEDIUMINT UNSIGNED,     #No reference but links to POST_NUM
INTEREST TINYINT     # 0 = Normal, 1 = High Interest, 2 = Ignore
);

#Friends and ignores
CREATE TABLE USER_PEER (
UID MEDIUMINT UNSIGNED REFERENCES user,
PEER_UID MEDIUMINT UNSIGNED REFERENCES user,
RELATIONSHIP TINYINT # 1 = Friend, 2 = Ignore, (3 = Bozo)
);

# Allows user to set precedence of folders in Thread frame
CREATE TABLE USER_FOLDER ( 
UID MEDIUMINT UNSIGNED REFERENCES user, 
FID MEDIUMINT UNSIGNED REFERENCES folder,
INTEREST TINYINT      # 0 = Normal, 1 = High Interest, 2 = Low Interest
);

#Basic preferences for forum use
CREATE TABLE USER_PREFS (
UID MEDIUMINT UNSIGNED REFERENCES user,
FIRSTNAME VARCHAR(32),
LASTNAME VARCHAR(32),
HOMEPAGE_URL VARCHAR(255),
PIC_URL VARCHAR(255),
EMAIL_NOTIFY CHAR(1),
TIMEZONE TINYINT,    # -11 to 11
DL_SAVING CHAR(1),
MARK_AS_OF_INT CHAR(1),
POSTS_PER_PAGE TINYINT UNSIGNED);

#Profile sections lookup
CREATE TABLE PROFILE_SECTION (
PSID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(64));

#Profile items lookup
CREATE TABLE PROFILE_ITEM (
PIID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
PSID MEDIUMINT UNSIGNED REFERENCES profile_section,
NAME VARCHAR(64));

#User profile entries
CREATE TABLE USER_PROFILE (
UID MEDIUMINT UNSIGNED REFERENCES user,
PIID MEDIUMINT UNSIGNED REFERENCES profile_item,
ENTRY VARCHAR(255));
