# ======================================================================
# Copyright Project BeehiveForum 2002
#
# This file is part of BeehiveForum.
#
# BeehiveForum is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# BeehiveForum is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Beehive; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
# USA
# ======================================================================
#
# $Id: upgrade.sql,v 1.3 2004-05-11 20:01:21 decoyduck Exp $

ALTER TABLE ADMIN_LOG RENAME {forum_webtag}_ADMIN_LOG;
ALTER TABLE BANNED_IP RENAME {forum_webtag}_BANNED_IP;
ALTER TABLE DEDUPE RENAME {forum_webtag}_DEDUPE;
ALTER TABLE FILTER_LIST RENAME {forum_webtag}_FILTER_LIST;
ALTER TABLE FOLDER RENAME {forum_webtag}_FOLDER;
ALTER TABLE LINKS RENAME {forum_webtag}_LINKS;
ALTER TABLE LINKS_COMMENT RENAME {forum_webtag}_LINKS_COMMENT;
ALTER TABLE LINKS_FOLDERS RENAME {forum_webtag}_LINKS_FOLDERS;
ALTER TABLE LINKS_VOTE RENAME {forum_webtag}_LINKS_VOTE;
ALTER TABLE PM RENAME {forum_webtag}_PM;
ALTER TABLE PM_ATTACHMENT_IDS RENAME {forum_webtag}_PM_ATTACHMENT_IDS;
ALTER TABLE PM_CONTENT RENAME {forum_webtag}_PM_CONTENT;
ALTER TABLE POLL RENAME {forum_webtag}_POLL;
ALTER TABLE POLL_VOTES RENAME {forum_webtag}_POLL_VOTES;
ALTER TABLE POST RENAME {forum_webtag}_POST;
ALTER TABLE POST_ATTACHMENT_FILES RENAME {forum_webtag}_POST_ATTACHMENT_FILES;
ALTER TABLE POST_ATTACHMENT_IDS RENAME {forum_webtag}_POST_ATTACHMENT_IDS;
ALTER TABLE POST_CONTENT RENAME {forum_webtag}_POST_CONTENT;
ALTER TABLE PROFILE_ITEM RENAME {forum_webtag}_PROFILE_ITEM;
ALTER TABLE PROFILE_SECTION RENAME {forum_webtag}_PROFILE_SECTION;
ALTER TABLE STATS RENAME {forum_webtag}_STATS;
ALTER TABLE THREAD RENAME {forum_webtag}_THREAD;
ALTER TABLE USER_FOLDER RENAME {forum_webtag}_USER_FOLDER;
ALTER TABLE USER_PEER RENAME {forum_webtag}_USER_PEER;
ALTER TABLE USER_POLL_VOTES RENAME {forum_webtag}_USER_POLL_VOTES;
ALTER TABLE USER_PROFILE RENAME {forum_webtag}_USER_PROFILE;
ALTER TABLE USER_PREFS RENAME {forum_webtag}_USER_PREFS;
ALTER TABLE USER_SIG RENAME {forum_webtag}_USER_SIG;
ALTER TABLE USER_THREAD RENAME {forum_webtag}_USER_THREAD;

CREATE TABLE {forum_webtag}_BANNED_IP_NEW (
  IP CHAR(15) NOT NULL DEFAULT '',
  PRIMARY KEY  (IP)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_BANNED_IP_NEW (IP) SELECT DISTINCT IP FROM {forum_webtag}_BANNED_IP;

DROP TABLE {forum_webtag}_BANNED_IP;

ALTER TABLE {forum_webtag}_BANNED_IP_NEW RENAME {forum_webtag}_BANNED_IP;

CREATE TABLE {forum_webtag}_LINKS_VOTE_NEW (
  LID SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  RATING SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  TSTAMP DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY  (LID, UID)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_LINKS_VOTE_NEW (LID, UID, RATING, TSTAMP)
SELECT DISTINCT LID, UID, RATING, TSTAMP FROM {forum_webtag}_LINKS_VOTE GROUP BY LID, UID;

DROP TABLE {forum_webtag}_LINKS_VOTE;

ALTER TABLE {forum_webtag}_LINKS_VOTE_NEW RENAME {forum_webtag}_LINKS_VOTE;

CREATE TABLE {forum_webtag}_POST_ATTACHMENT_IDS_NEW (
  TID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  AID CHAR(32) NOT NULL DEFAULT '',
  PRIMARY KEY  (TID,PID),
  KEY AID (AID)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_POST_ATTACHMENT_IDS_NEW (TID, PID, AID)
SELECT DISTINCT TID, PID, AID FROM {forum_webtag}_POST_ATTACHMENT_IDS GROUP BY TID, PID;

DROP TABLE {forum_webtag}_POST_ATTACHMENT_IDS;

ALTER TABLE {forum_webtag}_POST_ATTACHMENT_IDS_NEW RENAME {forum_webtag}_POST_ATTACHMENT_IDS;

CREATE TABLE {forum_webtag}_STATS_NEW (
  ID MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  MOST_USERS_DATE DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  MOST_USERS_COUNT MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  MOST_POSTS_DATE DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  MOST_POSTS_COUNT MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (ID)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_STATS_NEW (MOST_USERS_DATE, MOST_USERS_COUNT, MOST_POSTS_DATE, MOST_POSTS_COUNT)
SELECT DISTINCT MOST_USERS_DATE, MOST_USERS_COUNT, MOST_POSTS_DATE, MOST_POSTS_COUNT
FROM {forum_webtag}_STATS;

DROP TABLE {forum_webtag}_STATS;

ALTER TABLE {forum_webtag}_STATS_NEW RENAME {forum_webtag}_STATS;

CREATE TABLE {forum_webtag}_USER_FOLDER_NEW (
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  FID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  INTEREST TINYINT(4) DEFAULT '0',
  ALLOWED TINYINT(4) DEFAULT '0',
  PRIMARY KEY  (UID,FID)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_USER_FOLDER_NEW (UID, FID, INTEREST, ALLOWED)
SELECT DISTINCT UID, FID, INTEREST, ALLOWED FROM {forum_webtag}_USER_FOLDER
GROUP BY UID, FID;

DROP TABLE {forum_webtag}_USER_FOLDER;

ALTER TABLE {forum_webtag}_USER_FOLDER_NEW RENAME {forum_webtag}_USER_FOLDER;

CREATE TABLE {forum_webtag}_USER_PEER_NEW (
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PEER_UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  RELATIONSHIP TINYINT(4) DEFAULT NULL,
  PRIMARY KEY  (UID,PEER_UID)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_USER_PEER_NEW (UID, PEER_UID, RELATIONSHIP)
SELECT DISTINCT UID, PEER_UID, RELATIONSHIP FROM {forum_webtag}_USER_PEER
GROUP BY UID, PEER_UID;

DROP TABLE {forum_webtag}_USER_PEER;

ALTER TABLE {forum_webtag}_USER_PEER_NEW RENAME {forum_webtag}_USER_PEER;

CREATE TABLE {forum_webtag}_USER_PREFS_NEW (
  UID MEDIUMINT UNSIGNED DEFAULT '0' NOT NULL,
  FIRSTNAME VARCHAR(32) NOT NULL,
  LASTNAME VARCHAR(32) NOT NULL,
  DOB DATE DEFAULT '0000-00-00' NOT NULL,
  HOMEPAGE_URL VARCHAR(255) NOT NULL,
  PIC_URL VARCHAR(255) NOT NULL,
  EMAIL_NOTIFY CHAR(1) DEFAULT 'Y' NOT NULL,
  TIMEZONE DECIMAL(2, 1) DEFAULT '0.0' NOT NULL,
  DL_SAVING CHAR(1) DEFAULT 'N' NOT NULL,
  MARK_AS_OF_INT CHAR(1) DEFAULT 'Y' NOT NULL,
  POSTS_PER_PAGE TINYINT(3) UNSIGNED DEFAULT '20' NOT NULL,
  FONT_SIZE TINYINT(3) UNSIGNED DEFAULT '10' NOT NULL,
  STYLE VARCHAR(255) NOT NULL,
  EMOTICONS VARCHAR(255) NOT NULL,
  VIEW_SIGS CHAR(1) DEFAULT 'Y' NOT NULL,
  START_PAGE TINYINT(3) UNSIGNED DEFAULT '0' NOT NULL,
  LANGUAGE VARCHAR(32) NOT NULL,
  PM_NOTIFY CHAR(1) DEFAULT 'Y' NOT NULL,
  PM_NOTIFY_EMAIL CHAR(1) DEFAULT 'Y' NOT NULL,
  DOB_DISPLAY TINYINT(3) UNSIGNED DEFAULT '2' NOT NULL,
  ANON_LOGON TINYINT(3) UNSIGNED DEFAULT '0' NOT NULL,
  SHOW_STATS TINYINT(3) UNSIGNED DEFAULT '1' NOT NULL,
  IMAGES_TO_LINKS CHAR(1) DEFAULT 'N' NOT NULL,
  USE_WORD_FILTER CHAR(1) DEFAULT 'N' NOT NULL,
  USE_ADMIN_FILTER CHAR(1) DEFAULT 'N' NOT NULL,
  ALLOW_EMAIL CHAR(1) DEFAULT 'Y' NOT NULL,
  ALLOW_PM CHAR(1) DEFAULT 'Y' NOT NULL,
  PRIMARY KEY (UID)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_USER_PREFS_NEW (UID, FIRSTNAME, LASTNAME, DOB, HOMEPAGE_URL, PIC_URL,
EMAIL_NOTIFY, TIMEZONE, DL_SAVING, MARK_AS_OF_INT, POSTS_PER_PAGE, FONT_SIZE, STYLE,
VIEW_SIGS, START_PAGE, LANGUAGE, PM_NOTIFY, PM_NOTIFY_EMAIL, DOB_DISPLAY, ANON_LOGON,
SHOW_STATS) SELECT DISTINCT UID, FIRSTNAME, LASTNAME, DOB, HOMEPAGE_URL, PIC_URL,
EMAIL_NOTIFY, TIMEZONE, DL_SAVING, MARK_AS_OF_INT, POSTS_PER_PAGE, FONT_SIZE,
STYLE, VIEW_SIGS, START_PAGE, LANGUAGE, PM_NOTIFY, PM_NOTIFY_EMAIL, DOB_DISPLAY,
ANON_LOGON, SHOW_STATS FROM {forum_webtag}_USER_PREFS GROUP BY UID;

DROP TABLE {forum_webtag}_USER_PREFS;

ALTER TABLE {forum_webtag}_USER_PREFS_NEW RENAME {forum_webtag}_USER_PREFS;

CREATE TABLE {forum_webtag}_USER_PROFILE_NEW (
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PIID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  ENTRY VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY  (UID,PIID)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_USER_PROFILE_NEW (UID, PIID, ENTRY)
SELECT DISTINCT UID, PIID, ENTRY FROM {forum_webtag}_USER_PROFILE
GROUP BY UID, PIID;

DROP TABLE {forum_webtag}_USER_PROFILE;

ALTER TABLE {forum_webtag}_USER_PROFILE_NEW RENAME {forum_webtag}_USER_PROFILE;

CREATE TABLE {forum_webtag}_USER_SIG_NEW (
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  CONTENT TEXT,
  HTML CHAR(1) DEFAULT NULL,
  PRIMARY KEY  (UID)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_USER_SIG_NEW (UID, CONTENT, HTML)
SELECT DISTINCT UID, CONTENT, HTML FROM {forum_webtag}_USER_SIG
GROUP BY UID;

DROP TABLE {forum_webtag}_USER_SIG;

ALTER TABLE {forum_webtag}_USER_SIG_NEW RENAME {forum_webtag}_USER_SIG;

CREATE TABLE {forum_webtag}_USER_THREAD_NEW (
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0,
  TID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0,
  LAST_READ MEDIUMINT(8) UNSIGNED DEFAULT NULL,
  LAST_READ_AT DATETIME DEFAULT NULL,
  INTEREST TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (UID, TID)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_USER_THREAD_NEW (UID, TID, LAST_READ, LAST_READ_AT, INTEREST)
SELECT DISTINCT UID, TID, LAST_READ, LAST_READ_AT, INTEREST FROM {forum_webtag}_USER_THREAD GROUP BY UID, TID;

DROP TABLE {forum_webtag}_USER_THREAD;

ALTER TABLE {forum_webtag}_USER_THREAD_NEW RENAME {forum_webtag}_USER_THREAD;

ALTER TABLE {forum_webtag}_THREAD ADD ADMIN_LOCK DATETIME DEFAULT NULL;

ALTER TABLE {forum_webtag}_PM ADD NOTIFIED TINYINT(1) UNSIGNED DEFAULT '0' NOT NULL;
UPDATE {forum_webtag}_PM SET NOTIFIED = 1 WHERE TYPE > 1;

ALTER TABLE {forum_webtag}_POLL_VOTES DROP VOTES;

CREATE TABLE {forum_webtag}_FILTER_LIST_NEW (
  ID MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  UID MEDIUMINT(8) UNSIGNED NOT NULL {forum_webtag} '0',  
  MATCH_TEXT VARCHAR(255) NOT NULL {forum_webtag} '',
  REPLACE_TEXT VARCHAR(255) NOT NULL {forum_webtag} '',
  FILTER_OPTION TINYINT(1) UNSIGNED NOT NULL {forum_webtag} '0',
  PRIMARY KEY  (ID, UID)
) TYPE=MYISAM;

INSERT INTO {forum_webtag}_FILTER_LIST_NEW (ID, UID, MATCH_TEXT, REPLACE_TEXT, FILTER_OPTION)
SELECT DISTINCT ID, 0, FILTER, REPEAT('*', LENGTH(FILTER)), 1 FROM {forum_webtag}_FILTER_LIST;

DROP TABLE {forum_webtag}_FILTER_LIST;

ALTER TABLE {forum_webtag}_FILTER_LIST_NEW RENAME {forum_webtag}_FILTER_LIST;

ALTER TABLE SESSIONS ADD FID MEDIUMINT(8) UNSIGNED DEFAULT '0' NOT NULL;
ALTER TABLE SESSIONS ADD INDEX (FID);
ALTER TABLE SESSIONS ADD INDEX (UID);

CREATE TABLE FORUMS (
  FID mediumint(8) unsigned NOT NULL auto_increment,
  WEBTAG varchar(255) NOT NULL default '',
  DEFAULT_FORUM tinyint(4) NOT NULL default '0',
  ACCESS_LEVEL tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (FID)
) TYPE=MyISAM;

INSERT INTO FORUMS (WEBTAG, DEFAULT_FORUM) VALUES('DEFAULT', 1);

CREATE TABLE FORUM_SETTINGS (
  SID MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  FID MEDIUMINT(8) UNSIGNED NOT NULL,
  SNAME VARCHAR(255) NOT NULL,
  SVALUE VARCHAR(255) NOT NULL,
  INDEX (SID, FID)
) TYPE=MyISAM;

INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'forum_name', 'A Beehive Forum');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'forum_email', 'admin@abeehiveforum.net');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, '{forum_webtag}_style', 'default');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, '{forum_webtag}_emoticon', 'default');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, '{forum_webtag}_language', 'en');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'show_stats', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'show_links', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'auto_logon', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'show_pms', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'pm_allow_attachments', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'maximum_post_length', '6226');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'allow_post_editing', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'post_edit_time', '0');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'allow_polls', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'search_min_word_length', '3');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'attachments_enabled', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'attachments_dir', 'attachments');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'attachments_allow_embed', 'N');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'attachments_use_old_method', 'N');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'guest_account_active', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'session_cutoff', '86400');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'active_session_cutoff', '900');

CREATE TABLE VISITOR_LOG (
  UID MEDIUMINT(8) UNSIGNED NOT NULL,
  FID MEDIUMINT(8) UNSIGNED NOT NULL,
  LAST_LOGON DATETIME NOT NULL,
  PRIMARY KEY (UID, FID)
) TYPE=MyISAM;

INSERT INTO VISITOR_LOG (UID, FID, LAST_LOGON) SELECT UID, 1, LAST_LOGON FROM USER;

CREATE TABLE USER_STATUS (
  UID MEDIUMINT(8) UNSIGNED NOT NULL,
  FID MEDIUMINT(8) UNSIGNED NOT NULL,
  STATUS INT(16) NOT NULL,
  PRIMARY KEY (UID, FID)
) TYPE=MyISAM;

INSERT INTO USER_STATUS (UID, FID, STATUS) SELECT UID, 1, STATUS FROM USER;
INSERT INTO USER_STATUS (UID, FID, STATUS) VALUES (1, 0, 56);

ALTER TABLE USER DROP LAST_LOGON;
ALTER TABLE USER DROP LOGON_FROM;
ALTER TABLE USER DROP STATUS;

ALTER TABLE {forum_webtag}_POST_ATTACHMENT_FILES ADD DELETED TINYINT UNSIGNED DEFAULT '0' NOT NULL;

CREATE TABLE USER_FORUM (
  UID MEDIUMINT(8) UNSIGNED NOT NULL,
  FID MEDIUMINT(8) UNSIGNED NOT NULL,
  INTEREST TINYINT(4) DEFAULT '0',
  ALLOWED TINYINT(4) DEFAULT '0',
  PRIMARY KEY (UID, FID)
) TYPE = MYISAM;

DELETE FROM USER WHERE LOGON = 'GUEST' AND (PASSWD = MD5('GUEST') OR PASSWD = MD5('guest'));
