CREATE TABLE DEFAULT_THREAD_NEW (
  TID mediumint(8) unsigned NOT NULL auto_increment,
  FID mediumint(8) unsigned default NULL,
  BY_UID mediumint(8) unsigned default NULL,
  TITLE varchar(64) default NULL,
  LENGTH mediumint(8) unsigned default NULL,
  POLL_FLAG char(1) default NULL,
  MODIFIED datetime default NULL,
  CLOSED datetime default NULL,
  STICKY char(1) default NULL,
  STICKY_UNTIL datetime default NULL,
  ADMIN_LOCK datetime default NULL,
  PRIMARY KEY  (TID),
  KEY BY_UID (BY_UID),
  KEY FID (FID),
  FULLTEXT KEY TITLE (TITLE)
);

INSERT INTO DEFAULT_THREAD_NEW (TID, FID, BY_UID, TITLE, LENGTH, POLL_FLAG, MODIFIED, CLOSED, STICKY, STICKY_UNTIL, ADMIN_LOCK) SELECT THREAD.TID, THREAD.FID, POST.FROM_UID, THREAD.TITLE, THREAD.LENGTH, THREAD.POLL_FLAG, THREAD.MODIFIED, THREAD.CLOSED, THREAD.STICKY, THREAD.STICKY_UNTIL, THREAD.ADMIN_LOCK FROM DEFAULT_THREAD THREAD LEFT JOIN DEFAULT_POST POST ON (POST.TID = THREAD.TID AND POST.PID = 1);

DROP TABLE DEFAULT_THREAD;

ALTER TABLE DEFAULT_THREAD_NEW RENAME DEFAULT_THREAD;

CREATE TABLE DEFAULT_VISITOR_LOG (
  UID mediumint(8) unsigned NOT NULL default '0',
  LAST_LOGON datetime NOT NULL default '0000-00-00 00:00:00',
  PRIMARY KEY  (UID)
);

INSERT INTO DEFAULT_VISITOR_LOG (UID, LAST_LOGON) SELECT UID, LAST_LOGON FROM VISITOR_LOG GROUP BY UID;

DROP TABLE VISITOR_LOG;

DROP TABLE SESSIONS;

CREATE TABLE SESSIONS (
  HASH varchar(32) NOT NULL default '',
  UID mediumint(8) unsigned NOT NULL default '0',
  IPADDRESS varchar(15) NOT NULL default '',
  TIME datetime NOT NULL default '0000-00-00 00:00:00',
  FID mediumint(8) unsigned NOT NULL default '0',
  PRIMARY KEY  (HASH, UID, IPADDRESS)
);

ALTER TABLE USER_PREFS CHANGE TIMEZONE TIMEZONE DECIMAL(3,1) DEFAULT '0.0' NOT NULL;
