# Beehive Forum Database Creation
# version 0.4 to 0.5 Upgrade
# http://beehiveforum.sourceforge.net/
#
# Generation Time: Mar 16, 2004 at 00:17
#
# $Id: upgrade-04-to-05.sql,v 1.11 2004-05-11 20:01:20 decoyduck Exp $
#
# --------------------------------------------------------#

ALTER TABLE ADMIN_LOG RENAME DEFAULT_ADMIN_LOG;
ALTER TABLE BANNED_IP RENAME DEFAULT_BANNED_IP;
ALTER TABLE DEDUPE RENAME DEFAULT_DEDUPE;
ALTER TABLE FILTER_LIST RENAME DEFAULT_FILTER_LIST;
ALTER TABLE FOLDER RENAME DEFAULT_FOLDER;
ALTER TABLE LINKS RENAME DEFAULT_LINKS;
ALTER TABLE LINKS_COMMENT RENAME DEFAULT_LINKS_COMMENT;
ALTER TABLE LINKS_FOLDERS RENAME DEFAULT_LINKS_FOLDERS;
ALTER TABLE LINKS_VOTE RENAME DEFAULT_LINKS_VOTE;
ALTER TABLE PM RENAME DEFAULT_PM;
ALTER TABLE PM_ATTACHMENT_IDS RENAME DEFAULT_PM_ATTACHMENT_IDS;
ALTER TABLE PM_CONTENT RENAME DEFAULT_PM_CONTENT;
ALTER TABLE POLL RENAME DEFAULT_POLL;
ALTER TABLE POLL_VOTES RENAME DEFAULT_POLL_VOTES;
ALTER TABLE POST RENAME DEFAULT_POST;
ALTER TABLE POST_ATTACHMENT_FILES RENAME DEFAULT_POST_ATTACHMENT_FILES;
ALTER TABLE POST_ATTACHMENT_IDS RENAME DEFAULT_POST_ATTACHMENT_IDS;
ALTER TABLE POST_CONTENT RENAME DEFAULT_POST_CONTENT;
ALTER TABLE PROFILE_ITEM RENAME DEFAULT_PROFILE_ITEM;
ALTER TABLE PROFILE_SECTION RENAME DEFAULT_PROFILE_SECTION;
ALTER TABLE STATS RENAME DEFAULT_STATS;
ALTER TABLE THREAD RENAME DEFAULT_THREAD;
ALTER TABLE USER_FOLDER RENAME DEFAULT_USER_FOLDER;
ALTER TABLE USER_PEER RENAME DEFAULT_USER_PEER;
ALTER TABLE USER_POLL_VOTES RENAME DEFAULT_USER_POLL_VOTES;
ALTER TABLE USER_PROFILE RENAME DEFAULT_USER_PROFILE;
ALTER TABLE USER_PREFS RENAME DEFAULT_USER_PREFS;
ALTER TABLE USER_SIG RENAME DEFAULT_USER_SIG;
ALTER TABLE USER_THREAD RENAME DEFAULT_USER_THREAD;

CREATE TABLE DEFAULT_BANNED_IP_NEW (
  IP CHAR(15) NOT NULL DEFAULT '',
  PRIMARY KEY  (IP)
) TYPE=MYISAM;

INSERT INTO DEFAULT_BANNED_IP_NEW (IP) SELECT DISTINCT IP FROM DEFAULT_BANNED_IP;

DROP TABLE DEFAULT_BANNED_IP;

ALTER TABLE DEFAULT_BANNED_IP_NEW RENAME DEFAULT_BANNED_IP;

CREATE TABLE DEFAULT_LINKS_VOTE_NEW (
  LID SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  RATING SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  TSTAMP DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY  (LID, UID)
) TYPE=MYISAM;

INSERT INTO DEFAULT_LINKS_VOTE_NEW (LID, UID, RATING, TSTAMP) 
SELECT DISTINCT LID, UID, RATING, TSTAMP FROM DEFAULT_LINKS_VOTE GROUP BY LID, UID;

DROP TABLE DEFAULT_LINKS_VOTE;

ALTER TABLE DEFAULT_LINKS_VOTE_NEW RENAME DEFAULT_LINKS_VOTE;

CREATE TABLE DEFAULT_POST_ATTACHMENT_IDS_NEW (
  TID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  AID CHAR(32) NOT NULL DEFAULT '',
  PRIMARY KEY  (TID,PID),
  KEY AID (AID)
) TYPE=MYISAM;

INSERT INTO DEFAULT_POST_ATTACHMENT_IDS_NEW (TID, PID, AID)
SELECT DISTINCT TID, PID, AID FROM DEFAULT_POST_ATTACHMENT_IDS GROUP BY TID, PID;

DROP TABLE DEFAULT_POST_ATTACHMENT_IDS;

ALTER TABLE DEFAULT_POST_ATTACHMENT_IDS_NEW RENAME DEFAULT_POST_ATTACHMENT_IDS;

CREATE TABLE DEFAULT_STATS_NEW (
  ID MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  MOST_USERS_DATE DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  MOST_USERS_COUNT MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  MOST_POSTS_DATE DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  MOST_POSTS_COUNT MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (ID)
) TYPE=MYISAM;

INSERT INTO DEFAULT_STATS_NEW (MOST_USERS_DATE, MOST_USERS_COUNT, MOST_POSTS_DATE, MOST_POSTS_COUNT)
SELECT DISTINCT MOST_USERS_DATE, MOST_USERS_COUNT, MOST_POSTS_DATE, MOST_POSTS_COUNT
FROM DEFAULT_STATS;

DROP TABLE DEFAULT_STATS;

ALTER TABLE DEFAULT_STATS_NEW RENAME DEFAULT_STATS;

CREATE TABLE DEFAULT_USER_FOLDER_NEW (
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  FID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  INTEREST TINYINT(4) DEFAULT '0',
  ALLOWED TINYINT(4) DEFAULT '0',
  PRIMARY KEY  (UID,FID)
) TYPE=MYISAM;

INSERT INTO DEFAULT_USER_FOLDER_NEW (UID, FID, INTEREST, ALLOWED)
SELECT DISTINCT UID, FID, INTEREST, ALLOWED FROM DEFAULT_USER_FOLDER
GROUP BY UID, FID;

DROP TABLE DEFAULT_USER_FOLDER;

ALTER TABLE DEFAULT_USER_FOLDER_NEW RENAME DEFAULT_USER_FOLDER;

CREATE TABLE DEFAULT_USER_PEER_NEW (
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PEER_UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  RELATIONSHIP TINYINT(4) DEFAULT NULL,
  PRIMARY KEY  (UID,PEER_UID)
) TYPE=MYISAM;

INSERT INTO DEFAULT_USER_PEER_NEW (UID, PEER_UID, RELATIONSHIP)
SELECT DISTINCT UID, PEER_UID, RELATIONSHIP FROM DEFAULT_USER_PEER
GROUP BY UID, PEER_UID;

DROP TABLE DEFAULT_USER_PEER;

ALTER TABLE DEFAULT_USER_PEER_NEW RENAME DEFAULT_USER_PEER;

CREATE TABLE DEFAULT_USER_PREFS_NEW (
  UID MEDIUMINT UNSIGNED DEFAULT '0' NOT NULL,
  FIRSTNAME VARCHAR(32) NOT NULL,
  LASTNAME VARCHAR(32) NOT NULL,
  DOB DATE DEFAULT '0000-00-00' NOT NULL,
  HOMEPAGE_URL VARCHAR(255) NOT NULL,
  PIC_URL VARCHAR(255) NOT NULL,
  EMAIL_NOTIFY CHAR(1) DEFAULT 'Y' NOT NULL,
  TIMEZONE DECIMAL(2, 1) DEFAULT '0.0' NOT NULL,
  DL_SAVING CHAR(1) DEFAULT 'N' NOT NULL,
  MARK_AS_OF_INT CHAR(1) DEFAULT 'Y' NOT NULL,
  POSTS_PER_PAGE TINYINT(3) UNSIGNED DEFAULT '20' NOT NULL,
  FONT_SIZE TINYINT(3) UNSIGNED DEFAULT '10' NOT NULL,
  STYLE VARCHAR(255) NOT NULL,
  EMOTICONS VARCHAR(255) NOT NULL,
  VIEW_SIGS CHAR(1) DEFAULT 'Y' NOT NULL,
  START_PAGE TINYINT(3) UNSIGNED DEFAULT '0' NOT NULL,
  LANGUAGE VARCHAR(32) NOT NULL,
  PM_NOTIFY CHAR(1) DEFAULT 'Y' NOT NULL,
  PM_NOTIFY_EMAIL CHAR(1) DEFAULT 'Y' NOT NULL,
  DOB_DISPLAY TINYINT(3) UNSIGNED DEFAULT '2' NOT NULL,
  ANON_LOGON TINYINT(3) UNSIGNED DEFAULT '0' NOT NULL,
  SHOW_STATS TINYINT(3) UNSIGNED DEFAULT '1' NOT NULL,
  IMAGES_TO_LINKS CHAR(1) DEFAULT 'N' NOT NULL,
  USE_WORD_FILTER CHAR(1) DEFAULT 'N' NOT NULL,
  USE_ADMIN_FILTER CHAR(1) DEFAULT 'N' NOT NULL,
  ALLOW_EMAIL CHAR(1) DEFAULT 'Y' NOT NULL,
  ALLOW_PM CHAR(1) DEFAULT 'Y' NOT NULL,
  PRIMARY KEY (UID)
) TYPE=MYISAM;

INSERT INTO DEFAULT_USER_PREFS_NEW (UID, FIRSTNAME, LASTNAME, DOB, HOMEPAGE_URL, PIC_URL,
EMAIL_NOTIFY, TIMEZONE, DL_SAVING, MARK_AS_OF_INT, POSTS_PER_PAGE, FONT_SIZE, STYLE,
VIEW_SIGS, START_PAGE, LANGUAGE, PM_NOTIFY, PM_NOTIFY_EMAIL, DOB_DISPLAY, ANON_LOGON,
SHOW_STATS) SELECT DISTINCT UID, FIRSTNAME, LASTNAME, DOB, HOMEPAGE_URL, PIC_URL,
EMAIL_NOTIFY, TIMEZONE, DL_SAVING, MARK_AS_OF_INT, POSTS_PER_PAGE, FONT_SIZE,
STYLE, VIEW_SIGS, START_PAGE, LANGUAGE, PM_NOTIFY, PM_NOTIFY_EMAIL, DOB_DISPLAY,
ANON_LOGON, SHOW_STATS FROM DEFAULT_USER_PREFS GROUP BY UID;

DROP TABLE DEFAULT_USER_PREFS;

ALTER TABLE DEFAULT_USER_PREFS_NEW RENAME DEFAULT_USER_PREFS;

CREATE TABLE DEFAULT_USER_PROFILE_NEW (
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PIID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  ENTRY VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY  (UID,PIID)
) TYPE=MYISAM;

INSERT INTO DEFAULT_USER_PROFILE_NEW (UID, PIID, ENTRY)
SELECT DISTINCT UID, PIID, ENTRY FROM DEFAULT_USER_PROFILE
GROUP BY UID, PIID;

DROP TABLE DEFAULT_USER_PROFILE;

ALTER TABLE DEFAULT_USER_PROFILE_NEW RENAME DEFAULT_USER_PROFILE;

CREATE TABLE DEFAULT_USER_SIG_NEW (
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  CONTENT TEXT,
  HTML CHAR(1) DEFAULT NULL,
  PRIMARY KEY  (UID)
) TYPE=MYISAM;

INSERT INTO DEFAULT_USER_SIG_NEW (UID, CONTENT, HTML)
SELECT DISTINCT UID, CONTENT, HTML FROM DEFAULT_USER_SIG
GROUP BY UID;

DROP TABLE DEFAULT_USER_SIG;

ALTER TABLE DEFAULT_USER_SIG_NEW RENAME DEFAULT_USER_SIG;

CREATE TABLE DEFAULT_USER_THREAD_NEW (
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0,
  TID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0,
  LAST_READ MEDIUMINT(8) UNSIGNED DEFAULT NULL,
  LAST_READ_AT DATETIME DEFAULT NULL,
  INTEREST TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (UID, TID)
) TYPE=MYISAM;

INSERT INTO DEFAULT_USER_THREAD_NEW (UID, TID, LAST_READ, LAST_READ_AT, INTEREST) 
SELECT DISTINCT UID, TID, LAST_READ, LAST_READ_AT, INTEREST FROM DEFAULT_USER_THREAD GROUP BY UID, TID;

DROP TABLE DEFAULT_USER_THREAD;

ALTER TABLE DEFAULT_USER_THREAD_NEW RENAME DEFAULT_USER_THREAD;

ALTER TABLE DEFAULT_THREAD ADD ADMIN_LOCK DATETIME DEFAULT NULL;

ALTER TABLE DEFAULT_PM ADD NOTIFIED TINYINT(1) UNSIGNED DEFAULT '0' NOT NULL;
UPDATE DEFAULT_PM SET NOTIFIED = 1 WHERE TYPE > 1;

ALTER TABLE DEFAULT_POLL_VOTES DROP VOTES;

CREATE TABLE DEFAULT_FILTER_LIST_NEW (
  ID MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  UID MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',  
  MATCH_TEXT VARCHAR(255) NOT NULL DEFAULT '',
  REPLACE_TEXT VARCHAR(255) NOT NULL DEFAULT '',
  FILTER_OPTION TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY  (ID, UID)
) TYPE=MYISAM;

INSERT INTO DEFAULT_FILTER_LIST_NEW (ID, UID, MATCH_TEXT, REPLACE_TEXT, FILTER_OPTION)
SELECT DISTINCT ID, 0, FILTER, REPEAT('*', LENGTH(FILTER)), 1 FROM DEFAULT_FILTER_LIST;

DROP TABLE DEFAULT_FILTER_LIST;

ALTER TABLE DEFAULT_FILTER_LIST_NEW RENAME DEFAULT_FILTER_LIST;

ALTER TABLE SESSIONS ADD FID MEDIUMINT(8) UNSIGNED DEFAULT '0' NOT NULL;
ALTER TABLE SESSIONS ADD INDEX (FID);
ALTER TABLE SESSIONS ADD INDEX (UID);

CREATE TABLE FORUMS (
  FID mediumint(8) unsigned NOT NULL auto_increment,
  WEBTAG varchar(255) NOT NULL default '',
  DEFAULT_FORUM tinyint(4) NOT NULL default '0',
  ACCESS_LEVEL tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (FID)
) TYPE=MyISAM;

INSERT INTO FORUMS (WEBTAG, DEFAULT_FORUM) VALUES('DEFAULT', 1);

CREATE TABLE FORUM_SETTINGS (
  SID MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  FID MEDIUMINT(8) UNSIGNED NOT NULL,  
  SNAME VARCHAR(255) NOT NULL,
  SVALUE VARCHAR(255) NOT NULL,
  INDEX (SID, FID)
) TYPE=MyISAM;

INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'forum_name', 'A Beehive Forum');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'forum_email', 'admin@abeehiveforum.net');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'default_style', 'default');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'default_emoticon', 'default');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'default_language', 'en');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'show_stats', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'show_links', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'auto_logon', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'show_pms', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'pm_allow_attachments', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'maximum_post_length', '6226');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'allow_post_editing', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'post_edit_time', '0');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'allow_polls', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'search_min_word_length', '3');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'attachments_enabled', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'attachments_dir', 'attachments');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'attachments_allow_embed', 'N');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'attachments_use_old_method', 'N');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'guest_account_active', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'session_cutoff', '86400');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (0, 'active_session_cutoff', '900');

INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'forum_name', 'A Beehive Forum');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'forum_email', 'admin@abeehiveforum.net');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'default_style', 'default');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'default_emoticon', 'default');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'default_language', 'en');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'show_stats', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'show_links', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'auto_logon', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'show_pms', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'pm_allow_attachments', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'maximum_post_length', '6226');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'allow_post_editing', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'post_edit_time', '0');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'allow_polls', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'search_min_word_length', '3');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'attachments_enabled', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'attachments_dir', 'attachments');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'attachments_allow_embed', 'N');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'attachments_use_old_method', 'N');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'guest_account_active', 'Y');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'session_cutoff', '86400');
INSERT INTO FORUM_SETTINGS (FID, SNAME, SVALUE) VALUES (1, 'active_session_cutoff', '900');

CREATE TABLE VISITOR_LOG (
  UID MEDIUMINT(8) UNSIGNED NOT NULL,
  FID MEDIUMINT(8) UNSIGNED NOT NULL,
  LAST_LOGON DATETIME NOT NULL,
  PRIMARY KEY (UID, FID)
) TYPE=MyISAM;

INSERT INTO VISITOR_LOG (UID, FID, LAST_LOGON) SELECT UID, 1, LAST_LOGON FROM USER;

CREATE TABLE USER_STATUS (
  UID MEDIUMINT(8) UNSIGNED NOT NULL,
  FID MEDIUMINT(8) UNSIGNED NOT NULL,
  STATUS INT(16) NOT NULL,
  PRIMARY KEY (UID, FID)
) TYPE=MyISAM;

INSERT INTO USER_STATUS (UID, FID, STATUS) SELECT UID, 1, STATUS FROM USER;
INSERT INTO USER_STATUS (UID, FID, STATUS) VALUES (1, 0, 56);

ALTER TABLE USER DROP LAST_LOGON;
ALTER TABLE USER DROP LOGON_FROM;
ALTER TABLE USER DROP STATUS;

ALTER TABLE DEFAULT_POST_ATTACHMENT_FILES ADD DELETED TINYINT UNSIGNED DEFAULT '0' NOT NULL;

CREATE TABLE USER_FORUM (
  UID MEDIUMINT(8) UNSIGNED NOT NULL,
  FID MEDIUMINT(8) UNSIGNED NOT NULL,
  INTEREST TINYINT(4) DEFAULT '0',
  ALLOWED TINYINT(4) DEFAULT '0',
  PRIMARY KEY (UID, FID)
) TYPE = MYISAM;

DELETE FROM USER WHERE LOGON = 'GUEST' AND (PASSWD = MD5('GUEST') OR PASSWD = MD5('guest'));
