# Beehive Forum Database Creation
# version 0.3 to 0.4 Upgrade
# http://beehiveforum.sourceforge.net/
#
# Generation Time: Nov 09, 2003 at 03:58 PM
#
# $Id: upgrade-04-to-041.sql,v 1.6 2004-03-13 20:04:32 decoyduck Exp $
#
# --------------------------------------------------------#

ALTER TABLE THREAD ADD ADMIN_LOCK DATETIME;
UPDATE THREAD SET ADMIN_LOCK = 0 WHERE 1;

ALTER TABLE PM ADD NOTIFIED TINYINT(1) UNSIGNED DEFAULT '0' NOT NULL;
UPDATE PM SET NOTIFIED = 1 WHERE TYPE > 1;

ALTER TABLE POLL_VOTES DROP VOTES;
ALTER TABLE USER_PREFS ADD IMAGES_TO_LINKS CHAR(1);

ALTER TABLE USER_PREFS ADD USE_WORD_FILTER CHAR(1);
ALTER TABLE USER_PREFS ADD USE_ADMIN_FILTER CHAR(1);

ALTER TABLE FILTER_LIST ADD UID MEDIUMINT(8) UNSIGNED DEFAULT '0' NOT NULL;
ALTER TABLE FILTER_LIST CHANGE FILTER MATCH_TEXT VARCHAR(255) NOT NULL;
ALTER TABLE FILTER_LIST ADD REPLACE_TEXT VARCHAR(255) NOT NULL;
ALTER TABLE FILTER_LIST ADD PREG_EXPR TINYINT(1) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE SESSIONS ADD FID MEDIUMINT(8) UNSIGNED DEFAULT '0' NOT NULL;
ALTER TABLE SESSIONS ADD INDEX (FID);
ALTER TABLE SESSIONS ADD INDEX (UID);

CREATE TABLE FORUMS (
  FID MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  WEBTAG VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (FID)
) TYPE=MyISAM;

CREATE TABLE VISITOR_LOG (
  UID MEDIUMINT UNSIGNED NOT NULL,
  FID MEDIUMINT UNSIGNED NOT NULL,
  LAST_LOGON DATETIME NOT NULL,
  INDEX (UID)
) TYPE=MyISAM;

ALTER TABLE USER DROP LAST_LOGON;
ALTER TABLE USER DROP LOGON_FROM;
